name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get install libfontconfig-dev libx11-dev libxft-dev python3-docutils libimlib2-dev libexif-dev fontconfig libfreetype6-dev

    - name: build
      run: |
        ./build_sxiv.sh
        ./build_tig.sh
        ./build_st.sh
        ./build_uctags.sh
